base/urls.py
from django.urls import path
from . import views

urlpatterns = [path("", views.home, name="home")]

national-pm/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("teams/", include("teams.urls")),
    path("tasks/", include("tasks.urls")),
    path("projects/", include("projects.urls")),
    path("users/", include("users.urls")),
    path("", include("base.urls")),
    path("admin/", admin.site.urls),
]

tasks/urls.py
from django.urls import path, include
from . import views

urlpatterns = [
    path("", views.TaskListView.as_view(), name="all-tasks"),
    path("active/", views.ActiveTaskListView.as_view(), name="active-tasks"),
    path(
        "completed/",
        views.CompletedTaskListView.as_view(),
        name="completed-tasks",
    ),
    path(
        "unassigned/",
        views.UnassignedTaskListView.as_view(),
        name="unassigned-tasks",
    ),
    path("create/", views.TaskCreateView.as_view(), name="create-task"),
    path("task/<int:pk>/", views.TaskDetailView.as_view(), name="task-detail"),
    path(
        "task/<int:pk>/update/",
        views.TaskUpdateView.as_view(),
        name="task-update",
    ),
    path(
        "task/<int:pk>/assign/",
        views.TaskAssignView.as_view(),
        name="task-assign",
    ),
    path(
        "task/<int:pk>/assign-to-self/",
        views.TaskAssignToSelfView.as_view(),
        name="task-assign-to-self",
    ),
    path(
        "task/<int:pk>/complete/",
        views.TaskCompleteView.as_view(),
        name="task-complete",
    ),
    path(
        "task/<int:pk>/delete/",
        views.TaskDeleteView.as_view(),
        name="task-delete",
    ),
]

comments/models.py
from django.db import models
from tasks.models import Task
from django.contrib.auth.models import User
from projects.models import Project


class TaskComment(models.Model):

    author = models.ForeignKey(User, on_delete=models.PROTECT)
    text = models.TextField(verbose_name="comment")

    task = models.ForeignKey(Task, on_delete=models.CASCADE)

    date_created = models.DateTimeField(auto_now_add=True)
    date_modified = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"Task comment #{self.id}"


class ProjectComment(models.Model):

    author = models.ForeignKey(User, on_delete=models.PROTECT)
    text = models.TextField(verbose_name="comment")

    project = models.ForeignKey(Project, on_delete=models.CASCADE)

    date_created = models.DateTimeField(auto_now_add=True)
    date_modified = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"Project comment #{self.id}"

tasks/models.py
from django.db import models
from django.shortcuts import reverse
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError
from projects.models import Project
from teams.models import Team
from datetime import date


class Task(models.Model):
    PRIORITY_LEVELS = [
        (3, "Low"),
        (6, "Medium"),
        (9, "High"),
    ]

    title = models.CharField(max_length=100)
    description = models.TextField(blank=True)

    project = models.ForeignKey(Project, on_delete=models.CASCADE)
    team = models.ForeignKey(Team, on_delete=models.PROTECT)
    assigned_to = models.ForeignKey(
        User,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        verbose_name="Assign to",
    )

    priority_level = models.IntegerField(choices=PRIORITY_LEVELS, default=3)
    estimated_duration = models.DurationField(help_text="hh:mm")

    date_created = models.DateTimeField(auto_now_add=True)
    created_by = models.ForeignKey(
        User, on_delete=models.PROTECT, related_name="created_tasks",
    )  # Set to current user on form validation
    date_modified = models.DateTimeField(auto_now=True)
    modified_by = models.ForeignKey(
        User, on_delete=models.PROTECT, related_name="modified_tasks",
    )  # Set to current user on form validation
    date_due = models.DateField(help_text="dd/mm/yyyy")

    completed = models.BooleanField(default=False)
    date_completed = models.DateField(null=True, blank=True)
    completed_by = models.ForeignKey(
        User,
        on_delete=models.PROTECT,
        null=True,
        blank=True,
        related_name="completed_tasks",
    )  # Set to current user on form validation

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("task-detail", kwargs={"pk": self.pk})

    @property
    def days_till_due(self):
        difference = self.date_due - date.today()
        return difference.days

    # Model validation
    def clean(self):

        if hasattr(self, "project"):
            self.team = self.project.team

        if self.assigned_to and self.assigned_to not in self.team.members.all():
            msg = """The user who this task is assigned to must be part of
                    the project's team.
                """
            raise ValidationError(msg)

    # Authorization tests
    def team_has_member(self, user):
        return user in self.team.members.all()

    def team_leader_is(self, user):
        return user == self.team.leader

    def is_assigned_to(self, user):
        return user == self.assigned_to

    def was_created_by(self, user):
        return user == self.created_by

tasks/forms.py
from datetime import date
from django import forms
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError
from base.widgets import DateWidget, DurationWidget
from . import models
from base import custom_forms


class TaskForm(custom_forms.CustomModelForm):
    class Meta:
        model = models.Task
        fields = [
            "title",
            "description",
            "project",
            "priority_level",
            "estimated_duration",
            "date_due",
        ]
        widgets = {
            "title": forms.TextInput(attrs={"autocomplete": "off"}),
            "description": forms.Textarea(attrs={"autocomplete": "off"}),
            "estimated_duration": DurationWidget(),
            "date_due": DateWidget(),
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        user = self.request_user

        if not user.profile.is_manager:
            q = user.profile.get_related_projects()
            self.fields["project"].queryset = q

    def clean_project(self):
        project = self.cleaned_data["project"]
        user = self.request_user

        if not user.profile.is_manager:
            if user not in project.team.members.all():
                msg = """You do not have permission to assign a task to a
                project that you are not a part of.
                """
                raise ValidationError(msg, code="Forbidden")

        return project


class AssignTaskForm(custom_forms.CustomModelForm):
    class Meta:
        model = models.Task
        fields = ["assigned_to"]


class CompleteTaskForm(custom_forms.CustomModelForm):
    class Meta:
        model = models.Task
        fields = [
            "date_completed",
        ]
        widgets = {"date_completed": DateWidget()}

tasks/views.py
from datetime import date

from django.contrib.auth import mixins
from django.contrib.auth.models import User
from django.contrib.messages.views import SuccessMessageMixin
from django.views import View, generic
from django.urls import reverse

from comments import forms as comment_forms
from comments import views as comment_views

from . import forms
from .models import Task
from projects.models import Project


class TaskListView(mixins.LoginRequiredMixin, generic.ListView):
    """Shows a list of all users tasks"""

    model = Task

    def get_queryset(self):
        return Task.objects.filter(assigned_to=self.request.user)


class ActiveTaskListView(mixins.LoginRequiredMixin, generic.ListView):
    """Shows a list of users active tasks"""

    model = Task

    def get_queryset(self):
        return (
            Task.objects.filter(assigned_to=self.request.user)
            .filter(completed=False)
            .order_by("date_due", "-priority_level")
        )


class CompletedTaskListView(mixins.LoginRequiredMixin, generic.ListView):
    """Shows a list of users active tasks"""

    model = Task

    def get_queryset(self):
        return Task.objects.filter(assigned_to=self.request.user).filter(
            completed=True
        )


class UnassignedTaskListView(mixins.LoginRequiredMixin, generic.ListView):
    """Shows a list of tasks from projects where the user is the leader."""

    model = Task

    def get_queryset(self):
        q = Task.objects.none()

        for project in Project.objects.filter(team__leader=self.request.user):
            q = q | project.task_set.filter(assigned_to=None)

        return q.distinct().order_by("date_due", "-priority_level")


class TaskDetailView(
    mixins.LoginRequiredMixin,
    mixins.UserPassesTestMixin,
    generic.detail.SingleObjectMixin,
    View,
):
    model = Task

    def get(self, request, *args, **kwargs):
        view = TaskDetailDisplay.as_view()
        return view(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        view = comment_views.PostTaskComment.as_view()
        return view(request, *args, **kwargs)

    def test_func(self):
        task = self.get_object()
        user = self.request.user

        if user.profile.is_manager:
            return True
        if task.was_created_by(user):
            return True
        return task.team_has_member(self.request.user)


class TaskDetailDisplay(generic.DetailView):
    model = Task

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["form"] = comment_forms.TaskCommentForm(user=self.request.user)
        return context


class TaskCreateView(
    mixins.LoginRequiredMixin, SuccessMessageMixin, generic.CreateView,
):
    model = Task
    form_class = forms.TaskForm
    success_message = "Task #%(id)s was created successfully"

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs.update({"user": self.request.user})
        return kwargs

    def get_success_message(self, cleaned_data):
        return self.success_message % dict(cleaned_data, id=self.object.id,)

    def get_success_url(self):
        task = self.object
        if task.team.leader == self.request.user:
            return reverse("task-assign", kwargs={"pk": self.object.pk})
        return super().get_success_url()

    def form_valid(self, form):
        form.instance.created_by = self.request.user
        form.instance.modified_by = self.request.user
        return super().form_valid(form)


class TaskUpdateView(
    mixins.LoginRequiredMixin,
    mixins.UserPassesTestMixin,
    SuccessMessageMixin,
    generic.UpdateView,
):
    model = Task
    form_class = forms.TaskForm
    success_message = "Task #%(id)s was updated successfully"

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs.update({"user": self.request.user})
        return kwargs

    def get_success_message(self, cleaned_data):
        return self.success_message % dict(cleaned_data, id=self.object.id,)

    def form_valid(self, form):
        form.instance.modified_by = self.request.user
        return super().form_valid(form)

    def test_func(self):
        task = self.get_object()
        user = self.request.user

        if task.was_created_by(user):
            return True
        if task.is_assigned_to(user):
            return True
        return task.team_leader_is(user)


class TaskAssignView(
    mixins.LoginRequiredMixin,
    mixins.UserPassesTestMixin,
    SuccessMessageMixin,
    generic.UpdateView,
):
    model = Task
    form_class = forms.AssignTaskForm

    success_message = "Task #%(id)s was assigned successfully"

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs.update({"user": self.request.user})
        return kwargs

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        task = context["object"]
        context["form"].fields["assigned_to"].queryset = User.objects.filter(
            team=task.team
        )
        return context

    def get_success_message(self, cleaned_data):
        return self.success_message % dict(cleaned_data, id=self.object.id,)

    def form_valid(self, form):
        form.instance.modified_by = self.request.user
        return super().form_valid(form)

    def test_func(self):
        task = self.get_object()
        user = self.request.user

        return task.team_leader_is(user)


class TaskAssignToSelfView(
    mixins.LoginRequiredMixin,
    mixins.UserPassesTestMixin,
    SuccessMessageMixin,
    generic.UpdateView,
):
    model = Task
    form_class = forms.AssignTaskForm

    success_message = "Task #%(id)s was assigned successfully"

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs.update({"user": self.request.user})
        return kwargs

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        task = context["object"]
        context["form"].fields["assigned_to"].disabled = True
        return context

    def get_initial(self):
        initial_data = super().get_initial()
        initial_data["assigned_to"] = self.request.user.pk
        return initial_data

    def get_success_message(self, cleaned_data):
        return self.success_message % dict(cleaned_data, id=self.object.id,)

    def form_valid(self, form):
        # There appears to be a bug in Django where setting the initial field to
        # a models instance stops it from getting passed on when the field is
        # disabled. hence we need to reset it here.
        form.instance.assigned_to = self.request.user
        form.instance.modified_by = self.request.user
        return super().form_valid(form)

    def test_func(self):
        task = self.get_object()
        user = self.request.user

        return task.team_has_member(user)


class TaskCompleteView(
    mixins.LoginRequiredMixin,
    mixins.UserPassesTestMixin,
    SuccessMessageMixin,
    generic.UpdateView,
):
    model = Task
    form_class = forms.CompleteTaskForm
    initial = {
        "date_completed": date.today,
    }
    success_message = "Task #%(id)s completed"

    def get_success_message(self, cleaned_data):
        return self.success_message % dict(cleaned_data, id=self.object.id,)

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs.update({"user": self.request.user})
        return kwargs

    def form_valid(self, form):
        form.instance.completed = True
        form.instance.completed_by = self.request.user
        form.instance.modified_by = self.request.user
        return super().form_valid(form)

    def test_func(self):
        task = self.get_object()
        user = self.request.user

        if task.was_created_by(user):
            return True
        if task.is_assigned_to(user):
            return True
        return task.team_leader_is(user)


class TaskDeleteView(
    mixins.LoginRequiredMixin, mixins.UserPassesTestMixin, generic.DeleteView,
):
    model = Task
    success_url = "/tasks"

    def test_func(self):
        task = self.get_object()
        user = self.request.user

        if user.profile.is_demo_user:
            return False
        if task.was_created_by(user):
            return True
        return task.team_leader_is(user)

tasks/templates/tasks/task_confirm_delete.html
{% extends 'base/base_detail.html' %}

{% block title %}
  <title>Delete Task {{ task.id }} | National - PMS</title>
{% endblock title %}

{% block nav %}
  {% include 'tasks/task_nav.html' %}
{% endblock nav %}

{% block cardContent %}
  <div class="card-header">
    <h2>Delete Task</h2>
  </div>

  <div class="card-body">
    <form method="post">
      {% csrf_token %}

      <h4 class="mb-3">
        Are you sure you want to delete Task #{{ object.id }} '{{ object.title }}'?
      </h4>

      <button type="submit" class="btn btn-danger">Delete</button>
      <a href="{% url 'task-detail' object.id %}" class="btn btn-secondary">Cancel</a>
    </form>
  </div>
{% endblock cardContent %}

tasks/templates/tasks/task_detail.html
{% extends 'base/base_detail.html' %}

{% load duration_filters %}

{% block title %}
  <title>Task {{ task.id }} | National - PMS</title>
{% endblock title %}

{% block nav %}
  {% include 'tasks/task_nav.html' %}
{% endblock nav %}



{% block cardContent %}
  <div class="card-header">
    <h2>Task ID: {{ task.id }}&emsp;Task Name: {{ task.title }}</h2>
  </div>

  <div class="d-flex border-bottom">
    <div class="col-4" style="padding: 0.75rem 1.25rem">
      <strong>Project:</strong>&emsp;
      <a href="{% url 'project-detail' task.project.id %}">{{ task.project }}</a>
    </div>
    <div class="col-4 border-left" style="padding: 0.75rem 1.25rem">
      <strong>Team:</strong>&emsp;
      <a href="{% url 'team-detail' task.team.id %}">{{ task.team }}</a>
    </div>
    <div class="col-4 border-left" style="padding: 0.75rem 1.25rem">
      <strong>Assigned to:</strong>&emsp;
      {% if task.assigned_to %}
        <a href="{% url 'profile' task.assigned_to %}">{{ task.assigned_to }}</a>
      {% else %}
        <div class="text-danger">Unassigned</div>
      {% endif %}
    </div>
  </div>

  <div class="card-body">
    <h4>Detail</h4>
    <p>
      {% if task.description %}
        {{ task.description }}
      {% else %}
        <small class="text-muted">This task does not have a description yet.</small>
      {% endif %}
    </p>
  </div>

  <ul class="list-group list-group-flush border">
    <li
      {% if task.priority_level <= 3 %}
        class="list-group-item border-top list-group-item-success"
      {% elif task.priority_level <= 6 %}
        class="list-group-item border-top  list-group-item-warning"
      {% elif task.priority_level <= 9 %}
        class="list-group-item border-top  list-group-item-danger"
      {% endif %}>
      <strong>Priority:</strong>&emsp;{{ task.get_priority_level_display }}
    </li>
    <li class="list-group-item">
      <strong>Estimated duration:</strong>&emsp;
      {{ task.estimated_duration|readable_duration:"{hours}h {minutes}min" }}
    </li>
  </ul>

  <div class="d-flex border-bottom">
    <div class="col-6" style="padding: 0.75rem 1.25rem">
      <strong>Date created:</strong>&emsp;{{ task.date_created }}
    </div>
    <div class="col-6 border-left" style="padding: 0.75rem 1.25rem">
      <strong>Created by:</strong>&emsp;
      <a href="{% url 'profile' task.created_by %}">{{ task.created_by }}</a>
    </div>
  </div>

  <div class="d-flex border-bottom">
    <div class="col-6" style="padding: 0.75rem 1.25rem">
      <strong>Last modified:</strong>&emsp;{{ task.date_modified }}
    </div>
    <div class="col-6 border-left" style="padding: 0.75rem 1.25rem">
      <strong>Modified by:</strong>&emsp;<a href="{% url 'profile' task.modified_by %}">{{ task.modified_by }}</a>
    </div>
  </div>

  <ul class="list-group list-group-flush border">
    <li class="list-group-item">
      <strong>Due:</strong>&emsp;{{ task.date_due }}&emsp;({{ task.date_due|timeuntil }})
    </li>
  </ul>

  <div class="d-flex">
    {% if task.completed %}
      <div class="col-4 list-group-item-success" style="padding: 0.75rem 1.25rem">
        <strong>Status:</strong>&emsp;Completed
      </div>
      <div class="col-4 list-group-item-success border-left" style="padding: 0.75rem 1.25rem">
        <strong>Date completed:</strong>&emsp;{{ task.date_completed }}
      </div>
      <div class="col-4 list-group-item-success border-left" style="padding: 0.75rem 1.25rem">
        <strong>Completed by:</strong>&emsp;<a href="{% url 'profile' task.completed_by %}">{{ task.completed_by }}</a>
      </div>
    {% else %}
      <div class="flex-fill" style="padding: 0.75rem 1.25rem">
        <strong>Status:</strong>&emsp;In-Progress
      </div>
    {% endif %}
    </li>
  </div>
  <div class="card-footer">

    {% if request.user == task.team.leader or request.user == task.assigned_to or request.user == task.created_by %}
      <a class="btn btn-primary" href="{% url 'task-update' task.id %}">Update</a>

      {% if request.user == task.team.leader %}
        <a class="btn btn-primary" href="{% url 'task-assign' task.id %}">Assign</a>
      {% elif task.assigned_to == None and request.user in task.team.members.all %}
        <a class="btn btn-primary" href="{% url 'task-assign-to-self' task.id %}">Assign to yourself</a>
      {% endif %}

      {% if not task.completed %}
        <a class="btn btn-success" href="{% url 'task-complete' task.id %}">Complete</a>
      {% endif %}

      {% if request.user == task.team.leader or request.user == task.created_by %}
        {% if not request.user.profile.is_demo_user %}
          <a class="btn btn-danger float-right" href="{% url 'task-delete' task.id %}">Delete</a>
        {% endif %}
      {% endif %}

    {% elif task.assigned_to == None and request.user in task.team.members.all %}
      <a class="btn btn-primary" href="{% url 'task-assign-to-self' task.id %}">Assign to yourself</a>
    {% else %}
      <small class="text-muted">You do not have permission to edit this task.</small>
    {% endif %}


  </div>
{% endblock cardContent %}

{% block comments %}
  {% with task.taskcomment_set.all as comments %}
    {% include 'comments/comments.html' %}
  {% endwith %}
{% endblock comments %}

tasks/templates/tasks/task_form.html
{% extends 'base/base_detail.html' %}

{% load crispy_forms_tags %}

{% block title %}
  {% if task %}
    <title>Task {{ task.id }} | National - PMS</title>
  {% else %}
    <title>Create Task | National - PMS</title>
  {% endif %}
{% endblock title %}

{% block nav %}
  {% include 'tasks/task_nav.html' %}
{% endblock nav %}

{% block cardContent %}
  <div class="card-header">
  {% if task %}
    <h2>Task {{ task.id }}</h2>
  {% else %}
    <h2>Create Task</h2>
  {% endif %}
  </div>
  <div class="card-body">
    <form method="post">
      {% csrf_token %}

      {{ form|crispy }}

      <button type="submit" class="btn btn-primary">Save</button>
      <a class="btn btn-secondary" href="
        {% if request.resolver_match.url_name == 'create-task' %}
          {% url 'active-tasks' %}
        {% elif request.resolver_match.url_name == 'project-add-task' %}
          {% url 'active-projects' %}
        {% else %}
          {% url 'task-detail' object.id %}
        {% endif %}
      ">Cancel</a>
    </form>
  </div>
{% endblock cardContent %}

tasks/templates/tasks/task_list.html
{% extends 'base/base_list.html' %}

{% block title %}
  <title>Tasks | National - PMS</title>
{% endblock title %}

{% block nav %}
  {% include "tasks/task_nav.html" %}
{% endblock nav %}

{% block table %}
  <div class="row">
  {% if request.resolver_match.url_name == 'active-tasks'%}
    <div class="col-md-8">
      <h4>Active Tasks</h4>
      <p class="text-muted">Active tasks assigned to you</p>
    </div>
  {% elif request.resolver_match.url_name == 'completed-tasks'%}
    <div class="col-md-8">
      <h4>Completed Tasks</h4>
      <p class="text-muted">Completed tasks assigned to you</p>
    </div>
  {% elif request.resolver_match.url_name == 'all-tasks'%}
    <div class="col-md-8">
      <h4>All Tasks</h4>
      <p class="text-muted">All tasks assigned to you. Hint: try searching for 'active' or 'completed'</p>
    </div>
  {% elif request.resolver_match.url_name == 'unassigned-tasks'%}
    <div class="col-md-8">
      <h4>Unassigned Tasks</h4>
      <p class="text-muted">Unassigned tasks from projects that you are leading</p>
    </div>
  {% endif %}

  {% with table_id="table1" row=True %}
    {% include 'tasks/tables/user_task_table.html' %}
  {% endwith %}
{% endblock table %}

tasks/templates/tasks/task_nav.html
<a
  href="{% url 'create-task' %}"
  class="btn btn-outline-primary btn-block mb-3
    {% if request.resolver_match.url_name == 'create-task'%}active{% endif %}">
  New Task
</a>

<div class="card mb-3">
  <div class="card-header text-center">
    <strong>My tasks</strong>
  </div>
  <nav class="nav nav-pills flex-md-column">
    <a
      href="{% url 'active-tasks' %}"
      class="nav-link
        {% if request.resolver_match.url_name == 'active-tasks'%}active{% endif %}">
      Active
    </a>
    <a
      href="{% url 'completed-tasks' %}"
      class="nav-link
        {% if request.resolver_match.url_name == 'completed-tasks'%}active{% endif %}">
      Completed
    </a>
    <a
      href="{% url 'all-tasks' %}"
      class="nav-link
        {% if request.resolver_match.url_name == 'all-tasks'%}active{% endif %}">
      All
    </a>
  </nav>
</div>

<div class="card mb-3">
  <div class="card-header text-center">
    <strong>Manage tasks</strong>
  </div>
  <nav class="nav nav-pills flex-md-column">
    <a
      href="{% url 'unassigned-tasks' %}"
      class="nav-link
        {% if request.resolver_match.url_name == 'unassigned-tasks' %}active{% endif %}">
      Unassigned
    </a>
  </nav>
</div>