base/urls.py
from django.urls import path
from . import views

urlpatterns = [path("", views.home, name="home")]

national-pm/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("teams/", include("teams.urls")),
    path("tasks/", include("tasks.urls")),
    path("projects/", include("projects.urls")),
    path("users/", include("users.urls")),
    path("", include("base.urls")),
    path("admin/", admin.site.urls),
]

tasks/urls.py
from django.urls import path, include
from . import views

urlpatterns = [
    path("", views.TaskListView.as_view(), name="all-tasks"),
    path("active/", views.ActiveTaskListView.as_view(), name="active-tasks"),
    path(
        "completed/",
        views.CompletedTaskListView.as_view(),
        name="completed-tasks",
    ),
    path(
        "unassigned/",
        views.UnassignedTaskListView.as_view(),
        name="unassigned-tasks",
    ),
    path("create/", views.TaskCreateView.as_view(), name="create-task"),
    path("task/<int:pk>/", views.TaskDetailView.as_view(), name="task-detail"),
    path(
        "task/<int:pk>/update/",
        views.TaskUpdateView.as_view(),
        name="task-update",
    ),
    path(
        "task/<int:pk>/assign/",
        views.TaskAssignView.as_view(),
        name="task-assign",
    ),
    path(
        "task/<int:pk>/assign-to-self/",
        views.TaskAssignToSelfView.as_view(),
        name="task-assign-to-self",
    ),
    path(
        "task/<int:pk>/complete/",
        views.TaskCompleteView.as_view(),
        name="task-complete",
    ),
    path(
        "task/<int:pk>/delete/",
        views.TaskDeleteView.as_view(),
        name="task-delete",
    ),
]

tasks/models.py
from django.db import models
from django.shortcuts import reverse
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError
from projects.models import Project
from teams.models import Team
from datetime import date


class Task(models.Model):
    PRIORITY_LEVELS = [
        (3, "Low"),
        (6, "Medium"),
        (9, "High"),
    ]

    title = models.CharField(max_length=100)
    description = models.TextField(blank=True)

    project = models.ForeignKey(Project, on_delete=models.CASCADE)
    team = models.ForeignKey(Team, on_delete=models.PROTECT)
    assigned_to = models.ForeignKey(
        User,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        verbose_name="Assign to",
    )

    priority_level = models.IntegerField(choices=PRIORITY_LEVELS, default=3)
    estimated_duration = models.DurationField(help_text="hh:mm")

    date_created = models.DateTimeField(auto_now_add=True)
    created_by = models.ForeignKey(
        User, on_delete=models.PROTECT, related_name="created_tasks",
    )  # Set to current user on form validation
    date_modified = models.DateTimeField(auto_now=True)
    modified_by = models.ForeignKey(
        User, on_delete=models.PROTECT, related_name="modified_tasks",
    )  # Set to current user on form validation
    date_due = models.DateField(help_text="dd/mm/yyyy")

    completed = models.BooleanField(default=False)
    date_completed = models.DateField(null=True, blank=True)
    completed_by = models.ForeignKey(
        User,
        on_delete=models.PROTECT,
        null=True,
        blank=True,
        related_name="completed_tasks",
    )  # Set to current user on form validation

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("task-detail", kwargs={"pk": self.pk})

    @property
    def days_till_due(self):
        difference = self.date_due - date.today()
        return difference.days

    # Model validation
    def clean(self):

        if hasattr(self, "project"):
            self.team = self.project.team

        if self.assigned_to and self.assigned_to not in self.team.members.all():
            msg = """The user who this task is assigned to must be part of
                    the project's team.
                """
            raise ValidationError(msg)

    # Authorization tests
    def team_has_member(self, user):
        return user in self.team.members.all()

    def team_leader_is(self, user):
        return user == self.team.leader

    def is_assigned_to(self, user):
        return user == self.assigned_to

    def was_created_by(self, user):
        return user == self.created_by

tasks/forms.py
from datetime import date
from django import forms
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError
from base.widgets import DateWidget, DurationWidget
from . import models
from base import custom_forms


class TaskForm(custom_forms.CustomModelForm):
    class Meta:
        model = models.Task
        fields = [
            "title",
            "description",
            "project",
            "priority_level",
            "estimated_duration",
            "date_due",
        ]
        widgets = {
            "title": forms.TextInput(attrs={"autocomplete": "off"}),
            "description": forms.Textarea(attrs={"autocomplete": "off"}),
            "estimated_duration": DurationWidget(),
            "date_due": DateWidget(),
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        user = self.request_user

        if not user.profile.is_manager:
            q = user.profile.get_related_projects()
            self.fields["project"].queryset = q

    def clean_project(self):
        project = self.cleaned_data["project"]
        user = self.request_user

        if not user.profile.is_manager:
            if user not in project.team.members.all():
                msg = """You do not have permission to assign a task to a
                project that you are not a part of.
                """
                raise ValidationError(msg, code="Forbidden")

        return project


class AssignTaskForm(custom_forms.CustomModelForm):
    class Meta:
        model = models.Task
        fields = ["assigned_to"]


class CompleteTaskForm(custom_forms.CustomModelForm):
    class Meta:
        model = models.Task
        fields = [
            "date_completed",
        ]
        widgets = {"date_completed": DateWidget()}

tasks/views.py
from datetime import date

from django.contrib.auth import mixins
from django.contrib.auth.models import User
from django.contrib.messages.views import SuccessMessageMixin
from django.views import View, generic
from django.urls import reverse

from comments import forms as comment_forms
from comments import views as comment_views

from . import forms
from .models import Task
from projects.models import Project


class TaskListView(mixins.LoginRequiredMixin, generic.ListView):
    """Shows a list of all users tasks"""

    model = Task

    def get_queryset(self):
        return Task.objects.filter(assigned_to=self.request.user)


class ActiveTaskListView(mixins.LoginRequiredMixin, generic.ListView):
    """Shows a list of users active tasks"""

    model = Task

    def get_queryset(self):
        return (
            Task.objects.filter(assigned_to=self.request.user)
            .filter(completed=False)
            .order_by("date_due", "-priority_level")
        )


class CompletedTaskListView(mixins.LoginRequiredMixin, generic.ListView):
    """Shows a list of users active tasks"""

    model = Task

    def get_queryset(self):
        return Task.objects.filter(assigned_to=self.request.user).filter(
            completed=True
        )


class UnassignedTaskListView(mixins.LoginRequiredMixin, generic.ListView):
    """Shows a list of tasks from projects where the user is the leader."""

    model = Task

    def get_queryset(self):
        q = Task.objects.none()

        for project in Project.objects.filter(team__leader=self.request.user):
            q = q | project.task_set.filter(assigned_to=None)

        return q.distinct().order_by("date_due", "-priority_level")


class TaskDetailView(
    mixins.LoginRequiredMixin,
    mixins.UserPassesTestMixin,
    generic.detail.SingleObjectMixin,
    View,
):
    model = Task

    def get(self, request, *args, **kwargs):
        view = TaskDetailDisplay.as_view()
        return view(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        view = comment_views.PostTaskComment.as_view()
        return view(request, *args, **kwargs)

    def test_func(self):
        task = self.get_object()
        user = self.request.user

        if user.profile.is_manager:
            return True
        if task.was_created_by(user):
            return True
        return task.team_has_member(self.request.user)


class TaskDetailDisplay(generic.DetailView):
    model = Task

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["form"] = comment_forms.TaskCommentForm(user=self.request.user)
        return context


class TaskCreateView(
    mixins.LoginRequiredMixin, SuccessMessageMixin, generic.CreateView,
):
    model = Task
    form_class = forms.TaskForm
    success_message = "Task #%(id)s was created successfully"

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs.update({"user": self.request.user})
        return kwargs

    def get_success_message(self, cleaned_data):
        return self.success_message % dict(cleaned_data, id=self.object.id,)

    def get_success_url(self):
        task = self.object
        if task.team.leader == self.request.user:
            return reverse("task-assign", kwargs={"pk": self.object.pk})
        return super().get_success_url()

    def form_valid(self, form):
        form.instance.created_by = self.request.user
        form.instance.modified_by = self.request.user
        return super().form_valid(form)


class TaskUpdateView(
    mixins.LoginRequiredMixin,
    mixins.UserPassesTestMixin,
    SuccessMessageMixin,
    generic.UpdateView,
):
    model = Task
    form_class = forms.TaskForm
    success_message = "Task #%(id)s was updated successfully"

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs.update({"user": self.request.user})
        return kwargs

    def get_success_message(self, cleaned_data):
        return self.success_message % dict(cleaned_data, id=self.object.id,)

    def form_valid(self, form):
        form.instance.modified_by = self.request.user
        return super().form_valid(form)

    def test_func(self):
        task = self.get_object()
        user = self.request.user

        if task.was_created_by(user):
            return True
        if task.is_assigned_to(user):
            return True
        return task.team_leader_is(user)


class TaskAssignView(
    mixins.LoginRequiredMixin,
    mixins.UserPassesTestMixin,
    SuccessMessageMixin,
    generic.UpdateView,
):
    model = Task
    form_class = forms.AssignTaskForm

    success_message = "Task #%(id)s was assigned successfully"

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs.update({"user": self.request.user})
        return kwargs

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        task = context["object"]
        context["form"].fields["assigned_to"].queryset = User.objects.filter(
            team=task.team
        )
        return context

    def get_success_message(self, cleaned_data):
        return self.success_message % dict(cleaned_data, id=self.object.id,)

    def form_valid(self, form):
        form.instance.modified_by = self.request.user
        return super().form_valid(form)

    def test_func(self):
        task = self.get_object()
        user = self.request.user

        return task.team_leader_is(user)


class TaskAssignToSelfView(
    mixins.LoginRequiredMixin,
    mixins.UserPassesTestMixin,
    SuccessMessageMixin,
    generic.UpdateView,
):
    model = Task
    form_class = forms.AssignTaskForm

    success_message = "Task #%(id)s was assigned successfully"

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs.update({"user": self.request.user})
        return kwargs

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        task = context["object"]
        context["form"].fields["assigned_to"].disabled = True
        return context

    def get_initial(self):
        initial_data = super().get_initial()
        initial_data["assigned_to"] = self.request.user.pk
        return initial_data

    def get_success_message(self, cleaned_data):
        return self.success_message % dict(cleaned_data, id=self.object.id,)

    def form_valid(self, form):
        # There appears to be a bug in Django where setting the initial field to
        # a models instance stops it from getting passed on when the field is
        # disabled. hence we need to reset it here.
        form.instance.assigned_to = self.request.user
        form.instance.modified_by = self.request.user
        return super().form_valid(form)

    def test_func(self):
        task = self.get_object()
        user = self.request.user

        return task.team_has_member(user)


class TaskCompleteView(
    mixins.LoginRequiredMixin,
    mixins.UserPassesTestMixin,
    SuccessMessageMixin,
    generic.UpdateView,
):
    model = Task
    form_class = forms.CompleteTaskForm
    initial = {
        "date_completed": date.today,
    }
    success_message = "Task #%(id)s completed"

    def get_success_message(self, cleaned_data):
        return self.success_message % dict(cleaned_data, id=self.object.id,)

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs.update({"user": self.request.user})
        return kwargs

    def form_valid(self, form):
        form.instance.completed = True
        form.instance.completed_by = self.request.user
        form.instance.modified_by = self.request.user
        return super().form_valid(form)

    def test_func(self):
        task = self.get_object()
        user = self.request.user

        if task.was_created_by(user):
            return True
        if task.is_assigned_to(user):
            return True
        return task.team_leader_is(user)


class TaskDeleteView(
    mixins.LoginRequiredMixin, mixins.UserPassesTestMixin, generic.DeleteView,
):
    model = Task
    success_url = "/tasks"

    def test_func(self):
        task = self.get_object()
        user = self.request.user

        if user.profile.is_demo_user:
            return False
        if task.was_created_by(user):
            return True
        return task.team_leader_is(user)

tasks/templates/tasks/tables/generic_task_table.html
<div class="col-md-4 ml-auto mb-3 align-self-end">
  <input type="search" class="searchInput form-control" data-table-id="{{ table_id }}" placeholder="Search" aria-label="Search table">
</div>

{# An optional closing tag so that the search box can be included in a row #}
{% if row %}
  </div>
{% endif %}


<table id="{{ table_id }}" class="table table-hover">
  <thead>
    <tr>
      <th class="sortHeader" data-sorted="true" data-table-id="{{ table_id }}" data-col="0" data-type="number"
        scope="col">
        Task ID
      </th>
      <th class="sortHeader" data-sorted="false" data-table-id="{{ table_id }}" data-col="1" data-type="text" scope="col">
        Title
      </th>
      <th class="sortHeader" data-sorted="false" data-table-id="{{ table_id }}" data-col="2" data-type="text" scope="col">
        Project
      </th>
      <th class="sortHeader" data-sorted="false" data-table-id="{{ table_id }}" data-col="3" data-type="text" scope="col">
        Assigned to
      </th>
      <th class="sortHeader" data-sorted="false" data-table-id="{{ table_id }}" data-col="4" data-type="number"
        scope="col">
        Priority
      </th>
      <th class="sortHeader" data-sorted="false" data-table-id="{{ table_id }}" data-col="5" data-type="number"
        scope="col">
        Due in
      </th>
      <th class="sr-only" data-sorted="false" data-table-id="{{ table_id }}" data-col="6" data-type="text"
        scope="col">
        Status
      </th>
    </tr>
  </thead>
  <tbody>
    <!-- We add a rotation of 0 to table rows so that the stretched links apply to the appropriate area. -->
    {% for task in task_list %}
      <tr class="{% if task.completed %}table-success{% endif %}" style="transform: rotate(0);">
        <th scope="row" data-sort-value="{{ task.id }}">
          <a href="{% url 'task-detail' task.id %}" class="stretched-link"></a>
          {{ task.id }}
        </th>

        <td>{{ task.title }}</td>
        <td>{{ task.project }}</td>

        {% if task.assigned_to %}
          <td>{{ task.assigned_to }}</td>
        {% else %}
          <td class="text-danger ">Unassigned</td>
        {% endif %}

        {% if task.priority_level <= 3 %}
          <td class="text-success" data-sort-value="{{ task.priority_level }}">
            {{ task.get_priority_level_display }}
          </td>
        {% elif task.priority_level <= 6 %}
          <td class="text-warning" data-sort-value="{{ task.priority_level }}">
            {{ task.get_priority_level_display }}
          </td>
        {% elif task.priority_level <= 9 %}
          <td class="text-danger" data-sort-value="{{ task.priority_level }}">
            {{ task.get_priority_level_display }}
          </td>
        {% else %}
          <td data-sort-value="{{ task.priority_level }}">
            {{ task.get_priority_level_display }}
          </td>
        {% endif %}

        {% if task.days_till_due > 7 %}
          <td class="text-success" data-sort-value="{{ task.days_till_due }}">
            {{ task.days_till_due }}&nbsp;days
          </td>
        {% elif task.days_till_due > 0 and task.days_till_due <= 7 %}
          <td class="text-warning" data-sort-value="{{ task.days_till_due }}">
            {{ task.days_till_due }}&nbsp;days
          </td>
        {% else %}
          <td class="text-danger" data-sort-value="{{ task.days_till_due }}">
            {{ task.days_till_due }}&nbsp;days
          </td>
        {% endif %}

        <td class="sr-only">
          {% if task.completed %}
            Completed
          {% else %}
            Active
          {% endif %}
        </td>
      </tr>
    {% endfor %}
  </tbody>
</table>

{% if not task_list %}
  <p class="text-muted ml-3">No tasks to show</p>
{% endif %}

tasks/templates/tasks/tables/project_task_table.html
<div class="col-md-4 ml-auto mb-3 align-self-end">
    <input type="search" class="searchInput form-control" data-table-id="{{ table_id }}" placeholder="Search" aria-label="Search table">
</div>

{# An optional closing tag so that the search box can be included in a row #}
{% if row %}
  </div>
{% endif %}


<table id="{{ table_id }}" class="table table-hover">
  <thead>
    <tr>
      <th class="sortHeader" data-sorted="true" data-table-id="{{ table_id }}" data-col="0" data-type="number"
        scope="col">
        Task ID
      </th>
      <th class="sortHeader" data-sorted="false" data-table-id="{{ table_id }}" data-col="1" data-type="text" scope="col">
        Title
      </th>
      <th class="sortHeader" data-sorted="false" data-table-id="{{ table_id }}" data-col="2" data-type="text" scope="col">
        Assigned to
      </th>
      <th class="sortHeader" data-sorted="false" data-table-id="{{ table_id }}" data-col="3" data-type="number"
        scope="col">
        Priority
      </th>
      <th class="sortHeader" data-sorted="false" data-table-id="{{ table_id }}" data-col="4" data-type="number"
        scope="col">
        Due in
      </th>
      <th class="sr-only" data-sorted="false" data-table-id="{{ table_id }}" data-col="5" data-type="text"
        scope="col">
        Status
      </th>
    </tr>
  </thead>
  <tbody>
    <!-- We add a rotation of 0 to table rows so that the stretched links apply to the appropriate area. -->
    {% for task in task_list %}
      <tr class="{% if task.completed %}table-success{% endif %}" style="transform: rotate(0);">
        <th scope="row" data-sort-value="{{ task.id }}">
          <a href="{% url 'task-detail' task.id %}" class="stretched-link"></a>
          {{ task.id }}
        </th>

        <td>{{ task.title }}</td>

        {% if task.assigned_to %}
          <td>{{ task.assigned_to }}</td>
        {% else %}
          <td class="text-danger ">Unassigned</td>
        {% endif %}

        {% if task.priority_level <= 3 %}
          <td class="text-success" data-sort-value="{{ task.priority_level }}">
            {{ task.get_priority_level_display }}
          </td>
        {% elif task.priority_level <= 6 %}
          <td class="text-warning" data-sort-value="{{ task.priority_level }}">
            {{ task.get_priority_level_display }}
          </td>
        {% elif task.priority_level <= 9 %}
          <td class="text-danger" data-sort-value="{{ task.priority_level }}">
            {{ task.get_priority_level_display }}
          </td>
        {% else %}
          <td data-sort-value="{{ task.priority_level }}">
            {{ task.get_priority_level_display }}
          </td>
        {% endif %}

        {% if task.days_till_due > 7 %}
          <td class="text-success" data-sort-value="{{ task.days_till_due }}">
            {{ task.days_till_due }}&nbsp;days
          </td>
        {% elif task.days_till_due > 0 and task.days_till_due <= 7 %}
          <td class="text-warning" data-sort-value="{{ task.days_till_due }}">
            {{ task.days_till_due }}&nbsp;days
          </td>
        {% else %}
          <td class="text-danger" data-sort-value="{{ task.days_till_due }}">
            {{ task.days_till_due }}&nbsp;days
          </td>
        {% endif %}

        <td class="sr-only">
          {% if task.completed %}
            Completed
          {% else %}
            Active
          {% endif %}
        </td>
      </tr>
    {% endfor %}
  </tbody>
</table>

{% if not task_list %}
  <p class="text-muted ml-3">No tasks to show</p>
{% endif %}

tasks/templates/tasks/tables/user_task_table.html
<div class="col-md-4 ml-auto mb-3 align-self-end">
  <input type="search" class="searchInput form-control" data-table-id="{{ table_id }}" placeholder="Search" aria-label="Search table">
</div>

{# An optional closing tag so that the search box can be included in a row #}
{% if row %}
  </div>
{% endif %}


<table id="{{ table_id }}" class="table table-hover">
  <thead>
    <tr>
      <th class="sortHeader" data-sorted="true" data-table-id="{{ table_id }}" data-col="0" data-type="number"
        scope="col">
        Task ID
      </th>
      <th class="sortHeader" data-sorted="false" data-table-id="{{ table_id }}" data-col="1" data-type="text" scope="col">
        Title
      </th>
      <th class="sortHeader" data-sorted="false" data-table-id="{{ table_id }}" data-col="2" data-type="text" scope="col">
        Project
      </th>
      <th class="sortHeader" data-sorted="false" data-table-id="{{ table_id }}" data-col="3" data-type="number"
        scope="col">
        Priority
      </th>
      <th class="sortHeader" data-sorted="false" data-table-id="{{ table_id }}" data-col="4" data-type="number"
        scope="col">
        Due in
      </th>
      <th class="sr-only" data-sorted="false" data-table-id="{{ table_id }}" data-col="5" data-type="text"
        scope="col">
        Status
      </th>
    </tr>
  </thead>
  <tbody>
    <!-- We add a rotation of 0 to table rows so that the stretched links apply to the appropriate area. -->
    {% for task in task_list %}
      <tr class="{% if task.completed %}table-success{% endif %}" style="transform: rotate(0);">
        <th scope="row" data-sort-value="{{ task.id }}">
          <a href="{% url 'task-detail' task.id %}" class="stretched-link"></a>
          {{ task.id }}
        </th>

        <td>{{ task.title }}</td>
        <td>{{ task.project }}</td>

        {% if task.priority_level <= 3 %}
          <td class="text-success" data-sort-value="{{ task.priority_level }}">
            {{ task.get_priority_level_display }}
          </td>
        {% elif task.priority_level <= 6 %}
          <td class="text-warning" data-sort-value="{{ task.priority_level }}">
            {{ task.get_priority_level_display }}
          </td>
        {% elif task.priority_level <= 9 %}
          <td class="text-danger" data-sort-value="{{ task.priority_level }}">
            {{ task.get_priority_level_display }}
          </td>
        {% else %}
          <td data-sort-value="{{ task.priority_level }}">
            {{ task.get_priority_level_display }}
          </td>
        {% endif %}

        {% if task.days_till_due > 7 %}
          <td class="text-success" data-sort-value="{{ task.days_till_due }}">
            {{ task.days_till_due }}&nbsp;days
          </td>
        {% elif task.days_till_due > 0 and task.days_till_due <= 7 %}
          <td class="text-warning" data-sort-value="{{ task.days_till_due }}">
            {{ task.days_till_due }}&nbsp;days
          </td>
        {% else %}
          <td class="text-danger" data-sort-value="{{ task.days_till_due }}">
            {{ task.days_till_due }}&nbsp;days
          </td>
        {% endif %}

        <td class="sr-only">
          {% if task.completed %}
            Completed
          {% else %}
            Active
          {% endif %}
        </td>
      </tr>
    {% endfor %}
  </tbody>
</table>

{% if not task_list %}
  <p class="text-muted ml-3">No tasks to show</p>
{% endif %}