base/urls.py
from django.urls import path
from . import views

urlpatterns = [path("", views.home, name="home")]

national-pm/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("teams/", include("teams.urls")),
    path("tasks/", include("tasks.urls")),
    path("projects/", include("projects.urls")),
    path("users/", include("users.urls")),
    path("", include("base.urls")),
    path("admin/", admin.site.urls),
]

users/urls.py
from django.urls import path, include
from . import views
from django.contrib.auth import views as auth_views

urlpatterns = [
    path(
        "login/",
        auth_views.LoginView.as_view(template_name="users/login.html"),
        name="login",
    ),
    path(
        "logout/",
        auth_views.LogoutView.as_view(template_name="users/logout.html"),
        name="logout",
    ),
    path("register/", views.UserCreateView.as_view(), name="register"),
    path(
        "view/<str:username>/", views.UserDetailView.as_view(), name="profile"
    ),
    path("update/", views.UserUpdateView.as_view(), name="profile-update"),
    path("delete/", views.UserDeleteView.as_view(), name="profile-delete"),
    path(
        "login/demo-user/", views.demo_user_login_view, name="demo-user-login"
    ),
    path("dashboard/", views.DashboardView.as_view(), name="dashboard"),
    path('password_reset/', auth_views.PasswordResetView.as_view(
        template_name='users/password_reset_form.html',
        html_email_template_name='users/password_reset_email.html'
    ), name='password_reset'),

    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(
        template_name='users/password_reset_done.html'
    ), name='password_reset_done'),

    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(
        template_name='users/password_reset_confirm.html'
    ), name='password_reset_confirm'),

    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(
        template_name='users/password_reset_complete.html'
    ), name='password_reset_complete'),
]

projects/models.py
from datetime import date

from django.db import models
from django.shortcuts import reverse
from django.contrib.auth.models import User
from teams.models import Team


class Project(models.Model):

    name = models.CharField(max_length=100)
    description = models.TextField(blank=True)
    team = models.ForeignKey(Team, on_delete=models.PROTECT)
    technologies_used = models.CharField(max_length=100, blank=True, null=True)
    project_progress = models.CharField(max_length=100, blank=True, null=True)
    date_created = models.DateTimeField(auto_now_add=True)
    created_by = models.ForeignKey(
        User, on_delete=models.PROTECT, related_name="created_projects",
    )  # Set to current user on form validation
    date_modified = models.DateTimeField(auto_now=True)
    modified_by = models.ForeignKey(
        User, on_delete=models.PROTECT, related_name="modified_projects",
    )  # Set to current user on form validation
    date_due = models.DateField(null=True, blank=True)

    completed = models.BooleanField(default=False)
    date_completed = models.DateField(null=True, blank=True)
    completed_by = models.ForeignKey(
        User,
        on_delete=models.PROTECT,
        null=True,
        blank=True,
        related_name="completed_projects",
    )  # Set to current user on form validation

    @property
    def days_till_due(self):
        if self.date_due:
            difference = self.date_due - date.today()
            return difference.days
        return None

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("project-detail", kwargs={"pk": self.pk})

    # Authorization methods
    def team_has_member(self, user):
        return user in self.team.members.all()

    def leader_is(self, user):
        return user == self.team.leader

    def was_created_by(self, user):
        return user == self.created_by

tasks/models.py
from django.db import models
from django.shortcuts import reverse
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError
from projects.models import Project
from teams.models import Team
from datetime import date


class Task(models.Model):
    PRIORITY_LEVELS = [
        (3, "Low"),
        (6, "Medium"),
        (9, "High"),
    ]

    title = models.CharField(max_length=100)
    description = models.TextField(blank=True)

    project = models.ForeignKey(Project, on_delete=models.CASCADE)
    team = models.ForeignKey(Team, on_delete=models.PROTECT)
    assigned_to = models.ForeignKey(
        User,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        verbose_name="Assign to",
    )

    priority_level = models.IntegerField(choices=PRIORITY_LEVELS, default=3)
    estimated_duration = models.DurationField(help_text="hh:mm")

    date_created = models.DateTimeField(auto_now_add=True)
    created_by = models.ForeignKey(
        User, on_delete=models.PROTECT, related_name="created_tasks",
    )  # Set to current user on form validation
    date_modified = models.DateTimeField(auto_now=True)
    modified_by = models.ForeignKey(
        User, on_delete=models.PROTECT, related_name="modified_tasks",
    )  # Set to current user on form validation
    date_due = models.DateField(help_text="dd/mm/yyyy")

    completed = models.BooleanField(default=False)
    date_completed = models.DateField(null=True, blank=True)
    completed_by = models.ForeignKey(
        User,
        on_delete=models.PROTECT,
        null=True,
        blank=True,
        related_name="completed_tasks",
    )  # Set to current user on form validation

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("task-detail", kwargs={"pk": self.pk})

    @property
    def days_till_due(self):
        difference = self.date_due - date.today()
        return difference.days

    # Model validation
    def clean(self):

        if hasattr(self, "project"):
            self.team = self.project.team

        if self.assigned_to and self.assigned_to not in self.team.members.all():
            msg = """The user who this task is assigned to must be part of
                    the project's team.
                """
            raise ValidationError(msg)

    # Authorization tests
    def team_has_member(self, user):
        return user in self.team.members.all()

    def team_leader_is(self, user):
        return user == self.team.leader

    def is_assigned_to(self, user):
        return user == self.assigned_to

    def was_created_by(self, user):
        return user == self.created_by

teams/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User


class Team(models.Model):
    name = models.CharField(max_length=100)

    leader = models.ForeignKey(
        User, on_delete=models.PROTECT, related_name="leader_of_teams"
    )
    members = models.ManyToManyField(User)

    date_created = models.DateTimeField(auto_now_add=True)
    created_by = models.ForeignKey(
        User, on_delete=models.PROTECT, related_name="created_teams"
    )  # Set to current user at form validation
    date_modified = models.DateTimeField(auto_now=True)
    modified_by = models.ForeignKey(
        User, on_delete=models.PROTECT, related_name="modified_teams"
    )  # Set to current user at form validation

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("team-detail", kwargs={"pk": self.pk})

    # Authorization checks
    def has_member(self, user):
        return user in self.members.all()

    def leader_is(self, user):
        return user == self.leader

    def was_created_by(self, user):
        return user == self.created_by

    # Related objects
    def get_related_projects(self):
        return self.project_set.all()

    def get_related_tasks(self):
        related_projects = self.get_related_projects()

        if len(related_projects) > 0:
            q = related_projects[0].task_set.all()

            for project in related_projects[1:]:
                q = q | project.task_set.all()

            return q

users/models.py
from django.db import models
from django.contrib.auth.models import User
from projects.models import Project

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    roll_number = models.CharField(max_length=50, blank=True, null=True)
    college_name = models.CharField(max_length=100, blank=True, null=True)
    university_name = models.CharField(max_length=100, blank=True, null=True)
    is_manager = models.BooleanField(default=False)
    is_demo_user = models.BooleanField(default=False)

    def __str__(self):
        return self.user.username

    def get_connections(self):
        """A queryset of users who share a team with the user object."""
        q = User.objects.filter(pk=self.user.pk)
        for team in self.user.team_set.all():
            q = q | team.members.all()
        return q.distinct()

    def get_related_projects(self):
        q = Project.objects.none()
        for team in self.user.team_set.all():
            q = q | team.project_set.all()
        return q.distinct()

users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from .models import Profile
from django.contrib.auth.models import User
from django import forms
from django.contrib.auth.forms import UserCreationForm
from .models import Profile

class UserRegisterForm(UserCreationForm):
    roll_number = forms.CharField(max_length=50, required=False)
    college_name = forms.CharField(max_length=100, required=True, label="College Name")
    university_name = forms.CharField(max_length=100, required=False, label="University Name")
    class Meta:
        model = User
        fields = [
            "first_name",
            "last_name",
            "username",
            "college_name",
            "university_name",
            "roll_number",
            "email",
            "password1",
            "password2",  
        ]


from django import forms
from django.contrib.auth.forms import UserChangeForm as BaseUserChangeForm
from django.contrib.auth.models import User

class UserChangeForm(BaseUserChangeForm):
    new_password1 = forms.CharField(
        label="New Password",
        strip=False,
        widget=forms.PasswordInput,
        required=False,  # Password is not required for profile update
    )
    new_password2 = forms.CharField(
        label="Confirm New Password",
        widget=forms.PasswordInput,
        required=False,  # Password is not required for profile update
    )

    class Meta:
        model = User
        fields = [
            "username",
            "first_name",
            "last_name",
            "email",
        ]

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields.pop("password")

    def clean(self):
        cleaned_data = super().clean()
        new_password1 = cleaned_data.get("new_password1")
        new_password2 = cleaned_data.get("new_password2")

        if new_password1 and new_password2:
            if new_password1 != new_password2:
                raise forms.ValidationError("The new passwords do not match.")

        return cleaned_data

    def save(self, commit=True):
        user = super().save(commit=False)

        new_password1 = self.cleaned_data.get("new_password1")
        if new_password1:
            user.set_password(new_password1)

        if commit:
            user.save()
        return user

projects/views.py
from datetime import date
from django.contrib.auth import mixins
from django.contrib.messages.views import SuccessMessageMixin
from django.shortcuts import reverse
from django.views import View, generic
from comments import forms as comment_forms
from comments import views as comment_views
from tasks.views import TaskCreateView
from django.contrib.auth.mixins import LoginRequiredMixin
from . import forms
from .models import Project



class ProjectListView(mixins.LoginRequiredMixin, generic.ListView):
    """Shows a list of all user projects"""

    model = Project

    def get_queryset(self):
        return Project.objects.all()


class ActiveProjectListView(mixins.LoginRequiredMixin, generic.ListView):
    """Shows a list of users active projects"""

    model = Project

    def get_queryset(self):
        return Project.objects.filter(team__members=self.request.user).filter(
            completed=False
        )


class CompletedProjectListView(mixins.LoginRequiredMixin, generic.ListView):
    """Shows a list of users completed projects"""

    model = Project

    def get_queryset(self):
        return Project.objects.filter(team__members=self.request.user).filter(
            completed=True
        )


class ProjectDetailView(LoginRequiredMixin, generic.DetailView):
    model = Project

    def get(self, request, *args, **kwargs):
        view = ProjectDetailDisplay.as_view()
        return view(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        view = comment_views.PostProjectComment.as_view()
        return view(request, *args, **kwargs)
    
class ProjectDetailDisplay(generic.DetailView):
    model = Project

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["form"] = comment_forms.ProjectCommentForm(
            user=self.request.user
        )
        return context


class ProjectCreateView(
    mixins.LoginRequiredMixin, SuccessMessageMixin, generic.CreateView,
):
    model = Project
    form_class = forms.ProjectForm
    success_message = "Project #%(id)s was created successfully"

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs.update({"user": self.request.user})
        return kwargs

    def get_success_message(self, cleaned_data):
        return self.success_message % dict(cleaned_data, id=self.object.id,)

    def form_valid(self, form):
        form.instance.created_by = self.request.user
        form.instance.modified_by = self.request.user
        form.instance.technologies_used = form.cleaned_data["technologies_used"]
        return super().form_valid(form)


class ProjectUpdateView(
    mixins.LoginRequiredMixin,
    mixins.UserPassesTestMixin,
    SuccessMessageMixin,
    generic.UpdateView,
):
    model = Project
    form_class = forms.ProjectForm
    success_message = "Project #%(id)s was updated successfully"

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs.update({"user": self.request.user})
        return kwargs

    def get_success_message(self, cleaned_data):
        return self.success_message % dict(cleaned_data, id=self.object.id,)

    def form_valid(self, form):
        form.instance.modified_by = self.request.user
        form.instance.technologies_used = form.cleaned_data["technologies_used"]
        form.instance.project_progress = form.cleaned_data["project_progress"]
        return super().form_valid(form)

    def test_func(self):
        project = self.get_object()
        user = self.request.user

        if project.was_created_by(user):
            return True
        return project.leader_is(user)


class ProjectCompleteView(
    mixins.LoginRequiredMixin,
    mixins.UserPassesTestMixin,
    SuccessMessageMixin,
    generic.UpdateView,
):
    model = Project
    form_class = forms.CompleteProjectForm
    initial = {
        "date_completed": date.today(),
    }
    success_message = "Project #%(id)s completed"

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs.update({"user": self.request.user})
        return kwargs

    def get_success_message(self, cleaned_data):
        return self.success_message % dict(cleaned_data, id=self.object.id,)

    def form_valid(self, form):
        form.instance.completed = True
        form.instance.completed_by = self.request.user
        form.instance.modified_by = self.request.user
        return super().form_valid(form)

    def test_func(self):
        project = self.get_object()
        user = self.request.user

        if project.was_created_by(user):
            return True
        return project.leader_is(user)


class ProjectDeleteView(
    mixins.LoginRequiredMixin, mixins.UserPassesTestMixin, generic.DeleteView,
):
    model = Project
    success_url = "/projects"

    def test_func(self):
        project = self.get_object()
        user = self.request.user

        if user.profile.is_demo_user:
            return False
        if project.was_created_by(user):
            return True
        return project.leader_is(user)


class ProjectAddTaskView(TaskCreateView):
    success_message = (
        "Task #{task_id} was successfully added to project #{project_id}."
    )

    def get_initial(self):
        initial = super().get_initial()

        project_pk = self.kwargs["pk"]
        # project = Project.objects.get(pk=project_pk)

        initial["project"] = project_pk
        return initial

    def get_success_message(self, cleaned_data):
        return self.success_message.format(
            task_id=self.object.id, project_id=self.kwargs["pk"]
        )

users/templates/users/login.html
{% extends 'base/base_single_card_sea_bg.html' %}

{% load crispy_forms_tags %}

{% block title %}
  <title>Login | National - PMS</title>
{% endblock title %}



{% block cardContent %}
  <div class="card-header">
    <h2>Login</h2>
  </div>
  <div class="card-body">
    <form method="post" novalidate>
      {% csrf_token %}

      {{ form|crispy }}

      <button type="submit" class="btn btn-primary d-block mx-auto">Log in</button>
    </form>
  </div>
  <div class="card-footer">
    <small class="d-block">
      Don't have an account? <a href="{% url 'register' %}" class="text-success"> Register an account here!</a> or <a href="{% url 'demo-user-login' %}" class="text-warning" >login as a demo user</a> to try it out.
    </small>
    <small class="text-muted d-block">
     <a href="{% url 'password_reset' %}" class="text-danger">Forgot Your Password?</a>
    </small>
  </div>
{% endblock cardContent %}

users/templates/users/login_demo_user.html
{% extends 'base/base_single_card_sea_bg.html' %}

{% block title %}
  <title>Login | National - PMS</title>
{% endblock title %}

{% block cardContent %}
  <div class="card-header">
    <h4>Logging in as a demo user...</h4>
  </div>
  <div class="card-body">
    <form method="post">
      {% csrf_token %}

      <p>
        Note that demo users cannot create, update or delete anything on the site.
      </p>

      <button type="submit" class="btn btn-primary d-block mx-auto">Continue</button>
    </form>
  </div>
{% endblock cardContent %}

users/templates/users/logout.html
{% extends 'base/base_single_card.html' %}

{% block title %}
  <title>Logout | National - PMS</title>
{% endblock title %}

{% block cardHeader %}
  Logged out
{% endblock cardHeader %}

{% block cardContent %}
  <div class="card-header">
    Logged out
  </div>
  <div class="card-body">
    You have been succesfully logged out.
  </div>
  <div class="container text-center my-5">
    <a href="{% url 'home' %}" class="btn btn-primary btn-lg">Go to Home :)</a>
  </div>
{% endblock cardContent %}

users/templates/users/password_reset_complete.html
{% extends 'base/base.html' %}

{% block content %}
  <div class="container">
    <div class="row justify-content-center">
      <div class="col-md-6">
        <div class="alert alert-success" role="alert">
          Your password has been successfully reset. You can now <a href="{% url 'login' %}">login</a> with your new password.
        </div>
      </div>
    </div>
  </div>
{% endblock %}

users/templates/users/password_reset_confirm.html
{% extends "base/base.html" %}

{% block content %}
  <div class="container">
    <div class="row justify-content-center">
      <div class="col-md-6">
        <div class="card">
          <div class="card-header">
            <h2 class="text-center">Change your password</h2>
          </div>
          <div class="card-body">
            {% if validlink %}
              <form method="POST">
                {% csrf_token %}
                {{ form.as_p }}
                <div class="text-center">
                  <input type="submit" class="btn btn-primary" value="Change my password">
                </div>
              </form>
            {% else %}
              <p>The password reset link was invalid, possibly because it has already been used. Please request a new password reset.</p>
            {% endif %}
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

users/templates/users/password_reset_done.html
{% extends 'base/base.html' %}

{% block content %}
  <div class="container">
    <div class="row justify-content-center">
      <div class="col-md-6">
        <div class="alert alert-success" role="alert">
          Password reset email has been sent. Check your inbox and follow the instructions.
        </div>
      </div>
    </div>
  </div>
{% endblock %}

users/templates/users/password_reset_email.html
<p>Hello :) <img src="https://media.giphy.com/media/mGcNjsfWAjY5AEZNw6/giphy.gif" width="50"></p>

<p>You're receiving this email because you requested a password reset for your user account at National PMS</p>

<p>If you didn't request a password reset, please ignore this email.</p>

<p>Your username, in case you’ve forgotten: {{ user.username }}</p>

<p>Please go to the following page to reset your password:</p>

<p>{{ protocol }}://{{ domain }}{% url "password_reset_confirm" uidb64=uid token=token %}</p>

<p>Thanks,</p>

<p>National-PMS Team</p>
<p></p>

users/templates/users/user_dashboard.html
{% extends 'base/base.html' %}

{% load static %}

{% block title %}
  <title>Dashboard | National - PMS</title>
{% endblock title %}

{% block content %}
  <div class="container-fluid">
    <div class="row">
      <div class="col">
        {% include 'base/base_messages.html' %}
      </div>
    </div>

    <div class="row">
      <div class="col-lg mb-4">
        <div class="card border-primary h-100">
          <div class="card-body pb-0">
            <div class="row">
              <div class="col-md-12 mb-3 btn btn-outline-light border-0 text-dark text-left">
                <h4 class="card-title">Technologies Used</h4>
                <div>
                  <canvas id="technologiesChart"></canvas>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    
      <div class="col-lg mb-4">
        <div class="card border-primary h-100">
          <div class="card-body pb-0">
            <div class="row">
              <div class="col-md-8 mb-3 btn btn-outline-light border-0 text-dark text-left">
                <h4 class="card-title">Completed v/s Active projects</h4>
              </div>
            </div>
            <div>
              <canvas id="projectChart"></canvas>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="row">
      <div class="col-lg mb-4">
        <div class="card border-primary h-100">
          <div class="card-body pb-0">
            <div class="row">
            <div class="col-md-8 mb-3 btn btn-outline-light border-0 text-dark text-left">
              <a href="{% url 'active-tasks' %}" class="stretched-link"></a>
              <h4 class="card-title">Tasks</h4>
              <p class="text-muted mb-0">Tasks that have been assigned to you</p>
            </div>

            {% with table_id="table1" row=True %} {# To include closing row tag #}
              {% include 'tasks/tables/user_task_table.html' %}
            {% endwith %}
          </div>

          <div class="card-footer">
            <a href="{% url 'create-task' %}" class="btn btn-primary align-self-end">New task</a>
          </div>
        </div>
      </div>

      <div class="col-lg mb-4">
        <div class="card border-primary h-100">
          <div class="card-body pb-0">
            <div class="row">
            <div class="col-md-8 mb-3 btn btn-outline-light border-0 text-dark text-left">
              <a href="{% url 'unassigned-tasks' %}" class="stretched-link"></a>
              <h4>Unassigned Tasks</h4>
              <p class="text-muted mb-0">Unassigned tasks from projects led by you</p>
            </div>

            {% with table_id="table2" row=True task_list=unassigned_task_list %} {# To include closing row tag #}
              {% include 'tasks/tables/user_task_table.html' %}
            {% endwith %}
          </div>

          <div class="card-footer">
            <a href="{% url 'create-task' %}" class="btn btn-primary align-self-end">New task</a>
          </div>
        </div>
      </div>
    </div>

    <div class="row">
      <div class="col-lg mb-4">
        <div class="card border-primary h-100">
          <div class="card-body pb-0">
            <div class="row">
            <div class="col-md-8 mb-3 btn btn-outline-light border-0 text-dark text-left">
              <a href="{% url 'active-projects' %}" class="stretched-link"></a>
              <h4>Projects</h4>
              <p class="text-muted mb-0">Active projects that you are a part of</p>
            </div>

            {% with table_id="table3" row=True %} {# To include closing row tag #}
              {% include 'projects/tables/generic_project_table.html' %}
            {% endwith %}
          </div>
          <div class="card-footer">
            <a href="{% url 'create-project' %}" class="btn btn-primary align-self-end">New project</a>
          </div>
        </div>
      </div>

      <div class="col-lg mb-4">
        <div class="card border-primary h-100">
          <div class="card-body pb-0">
            <div class="row">
            <div class="col-md-8 mb-3 btn btn-outline-light border-0 text-dark text-left">
              <a href="{% url 'teams' %}" class="stretched-link"></a>
              <h4>Teams</h4>
              <p class="text-muted mb-0">Teams that you are a part of</p>
            </div>

            {% with table_id="table4" row=True %} {# To include closing row tag #}
              {% include 'teams/tables/generic_team_table.html' %}
            {% endwith %}
          </div>

          <div class="card-footer">
            <a href="{% url 'create-team' %}" class="btn btn-primary align-self-end">New team</a>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock content %}
{% block scripts %}
    {{ block.super }}
    <script src="{% static 'base/scripts/tableFunctions.js' %}"></script>
    <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
    <script>
        var chartLabels = {{ chart_labels|safe }};
        var chartData = {{ chart_data|safe }};

        var ctx = document.getElementById('technologiesChart').getContext('2d');
        var myChart = new Chart(ctx, {
            type: 'bar',
            data: {
                labels: chartLabels,
                datasets: [{
                    label: '' ,
                    data: chartData,
                    backgroundColor: [
      'rgba(255, 99, 132, 0.2)',
      'rgba(255, 159, 64, 0.2)',
      'rgba(255, 205, 86, 0.2)',
      'rgba(75, 192, 192, 0.2)',
      'rgba(54, 162, 235, 0.2)',
      'rgba(153, 102, 255, 0.2)',
      'rgba(201, 203, 207, 0.2)'
    ],
    borderColor: [
      'rgb(255, 99, 132)',
      'rgb(255, 159, 64)',
      'rgb(255, 205, 86)',
      'rgb(75, 192, 192)',
      'rgb(54, 162, 235)',
      'rgb(153, 102, 255)',
      'rgb(201, 203, 207)'
    ],
                    borderWidth: 2
                }]
            },
            options: {

 responsive: true, 
              plugins: {      
            legend: {
            display: false
         },
            subtitle: {
                display: true,
                text: 'Technologies used in all projects present in National-PMS.'
            }
        },  
                scales: {
                    y: {
                        beginAtZero: true,
                    
                    }
                },
animation: false
            }
        });
    </script>
    <script>
      var ctx = document.getElementById('projectChart').getContext('2d');
      var myChart = new Chart(ctx, {
          type: 'pie',
          data: {
              labels:['Completed', 'Active'],
              datasets: [{
                  label: '' ,
                  data: [{{ project_completed_counts }}, {{ project_active_counts }}],
                  backgroundColor: [
    'rgba(255, 99, 132, 0.2)',
    'rgba(255, 159, 64, 0.2)',
    'rgba(255, 205, 86, 0.2)',
    'rgba(75, 192, 192, 0.2)',
    'rgba(54, 162, 235, 0.2)',
    'rgba(153, 102, 255, 0.2)',
    'rgba(201, 203, 207, 0.2)'
  ],
  borderColor: [
    'rgb(255, 99, 132)',
    'rgb(255, 159, 64)',
    'rgb(255, 205, 86)',
    'rgb(75, 192, 192)',
    'rgb(54, 162, 235)',
    'rgb(153, 102, 255)',
    'rgb(201, 203, 207)'
  ],
                  borderWidth: 2
              }]
          },
          options: {
            maintainAspectRatio: false, // Disable aspect ratio
        responsive: true, 
            plugins: {      
          subtitle: {
              display: true,
              text: 'Pie chart shwoing completed v/s active projects present in National-PMS.'
          }
      },  
        
          }
      });
  </script>
{% endblock scripts %}

users/templates/users/user_detail.html
{% extends 'base/base_single_card.html' %}
{% load static %}

{% block title %}
  <title>Profile | National - PMS</title>
{% endblock title %}

{% block cardContent %}
  <div class="card-body">

        <dl class="row">
          <dt class="col-sm-3">Username:</dt>
          <dd class="col-sm-9">{{ user.username }}</dd>
          <dt class="col-sm-3">First Name:</dt>
          <dd class="col-sm-9">{{ user.first_name }}</dd>
          <dt class="col-sm-3">Last Name:</dt>
          <dd class="col-sm-9">{{ user.last_name }}</dd>
          <dt class="col-sm-3">Email:</dt>
          <dd class="col-sm-9">{{ user.email }}</dd>
          <dt class="col-sm-3">Roll Number:</dt>
          <dd class="col-sm-9">{{ user.profile.roll_number }}</dd>
          <dt class="col-sm-3">College Name:</dt>
          <dd class="col-sm-9"> {{ college_name }}</dd>
          <dt class="col-sm-3">University Name:</dt>
          <dd class="col-sm-9"> {{ university_name }}</dd>
        </dl>

    {% if user.profile.is_manager %}
      <p>
        Status:&emsp;Manager
      </p>
    {% endif %}
  </div>

  {% if not request.user.profile.is_demo_user %}
    {% if request.user == user%}
      <div class="card-footer">
        <a class="btn btn-primary" href="{% url 'profile-update' %}">Update</a>
        <a class="btn btn-danger float-right" href="{% url 'profile-delete' %}">Delete</a>
      </div>
    {% endif %}
  {% endif %}
{% endblock cardContent %}

{% block belowCard %}
  {% with user.task_set.all as task_list %}
    {% with user.profile.get_related_projects as project_list %}
      {% with user.team_set.all as team_list %}
        {% include 'users/user_objects_lists.html' %}
      {% endwith %}
    {% endwith %}
  {% endwith %}
{% endblock belowCard %}

{% block scripts %}
  {{ block.super }}
  <script src="{% static 'base/scripts/tableFunctions.js' %}"></script>
{% endblock scripts %}