base/urls.py
from django.urls import path
from . import views

urlpatterns = [path("", views.home, name="home")]

national-pm/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("teams/", include("teams.urls")),
    path("tasks/", include("tasks.urls")),
    path("projects/", include("projects.urls")),
    path("users/", include("users.urls")),
    path("", include("base.urls")),
    path("admin/", admin.site.urls),
]

projects/urls.py
from django.urls import path, include
from . import views

urlpatterns = [
    path("", views.ProjectListView.as_view(), name="all-projects"),
    path(
        "active/", views.ActiveProjectListView.as_view(), name="active-projects"
    ),
    path(
        "completed/",
        views.CompletedProjectListView.as_view(),
        name="completed-projects",
    ),
    path("create/", views.ProjectCreateView.as_view(), name="create-project"),
    path(
        "project/<int:pk>/",
        views.ProjectDetailView.as_view(),
        name="project-detail",
    ),
    path(
        "project/<int:pk>/update/",
        views.ProjectUpdateView.as_view(),
        name="project-update",
    ),
    path(
        "project/<int:pk>/complete/",
        views.ProjectCompleteView.as_view(),
        name="project-complete",
    ),
    path(
        "project/<int:pk>/delete/",
        views.ProjectDeleteView.as_view(),
        name="project-delete",
    ),
    path(
        "project/<int:pk>/addtask/",
        views.ProjectAddTaskView.as_view(),
        name="project-add-task",
    ),
]

comments/models.py
from django.db import models
from tasks.models import Task
from django.contrib.auth.models import User
from projects.models import Project


class TaskComment(models.Model):

    author = models.ForeignKey(User, on_delete=models.PROTECT)
    text = models.TextField(verbose_name="comment")

    task = models.ForeignKey(Task, on_delete=models.CASCADE)

    date_created = models.DateTimeField(auto_now_add=True)
    date_modified = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"Task comment #{self.id}"


class ProjectComment(models.Model):

    author = models.ForeignKey(User, on_delete=models.PROTECT)
    text = models.TextField(verbose_name="comment")

    project = models.ForeignKey(Project, on_delete=models.CASCADE)

    date_created = models.DateTimeField(auto_now_add=True)
    date_modified = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"Project comment #{self.id}"

projects/models.py
from datetime import date

from django.db import models
from django.shortcuts import reverse
from django.contrib.auth.models import User
from teams.models import Team


class Project(models.Model):

    name = models.CharField(max_length=100)
    description = models.TextField(blank=True)
    team = models.ForeignKey(Team, on_delete=models.PROTECT)
    technologies_used = models.CharField(max_length=100, blank=True, null=True)
    project_progress = models.CharField(max_length=100, blank=True, null=True)
    date_created = models.DateTimeField(auto_now_add=True)
    created_by = models.ForeignKey(
        User, on_delete=models.PROTECT, related_name="created_projects",
    )  # Set to current user on form validation
    date_modified = models.DateTimeField(auto_now=True)
    modified_by = models.ForeignKey(
        User, on_delete=models.PROTECT, related_name="modified_projects",
    )  # Set to current user on form validation
    date_due = models.DateField(null=True, blank=True)

    completed = models.BooleanField(default=False)
    date_completed = models.DateField(null=True, blank=True)
    completed_by = models.ForeignKey(
        User,
        on_delete=models.PROTECT,
        null=True,
        blank=True,
        related_name="completed_projects",
    )  # Set to current user on form validation

    @property
    def days_till_due(self):
        if self.date_due:
            difference = self.date_due - date.today()
            return difference.days
        return None

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("project-detail", kwargs={"pk": self.pk})

    # Authorization methods
    def team_has_member(self, user):
        return user in self.team.members.all()

    def leader_is(self, user):
        return user == self.team.leader

    def was_created_by(self, user):
        return user == self.created_by

tasks/models.py
from django.db import models
from django.shortcuts import reverse
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError
from projects.models import Project
from teams.models import Team
from datetime import date


class Task(models.Model):
    PRIORITY_LEVELS = [
        (3, "Low"),
        (6, "Medium"),
        (9, "High"),
    ]

    title = models.CharField(max_length=100)
    description = models.TextField(blank=True)

    project = models.ForeignKey(Project, on_delete=models.CASCADE)
    team = models.ForeignKey(Team, on_delete=models.PROTECT)
    assigned_to = models.ForeignKey(
        User,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        verbose_name="Assign to",
    )

    priority_level = models.IntegerField(choices=PRIORITY_LEVELS, default=3)
    estimated_duration = models.DurationField(help_text="hh:mm")

    date_created = models.DateTimeField(auto_now_add=True)
    created_by = models.ForeignKey(
        User, on_delete=models.PROTECT, related_name="created_tasks",
    )  # Set to current user on form validation
    date_modified = models.DateTimeField(auto_now=True)
    modified_by = models.ForeignKey(
        User, on_delete=models.PROTECT, related_name="modified_tasks",
    )  # Set to current user on form validation
    date_due = models.DateField(help_text="dd/mm/yyyy")

    completed = models.BooleanField(default=False)
    date_completed = models.DateField(null=True, blank=True)
    completed_by = models.ForeignKey(
        User,
        on_delete=models.PROTECT,
        null=True,
        blank=True,
        related_name="completed_tasks",
    )  # Set to current user on form validation

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("task-detail", kwargs={"pk": self.pk})

    @property
    def days_till_due(self):
        difference = self.date_due - date.today()
        return difference.days

    # Model validation
    def clean(self):

        if hasattr(self, "project"):
            self.team = self.project.team

        if self.assigned_to and self.assigned_to not in self.team.members.all():
            msg = """The user who this task is assigned to must be part of
                    the project's team.
                """
            raise ValidationError(msg)

    # Authorization tests
    def team_has_member(self, user):
        return user in self.team.members.all()

    def team_leader_is(self, user):
        return user == self.team.leader

    def is_assigned_to(self, user):
        return user == self.assigned_to

    def was_created_by(self, user):
        return user == self.created_by

projects/forms.py
from django import forms
from django.core.exceptions import ValidationError
from base import custom_forms
from base.widgets import DateWidget
from . import models

class ProjectForm(custom_forms.CustomModelForm):
    technologies_used = forms.MultipleChoiceField(
        choices=[
            ('Python', 'Python'),
            ('Java', 'Java'),
            ('JavaScript', 'JavaScript'),
            ('PHP', 'PHP'),
            ('Ruby', 'Ruby'),
            ('C#', 'C#'),
            ('HTML', 'HTML'),
            ('CSS', 'CSS'),
            ('SQL', 'SQL'),
            ('Android', 'Android'), 
            # ADD MORE TECHNOLOGIES HERE
            ('other', 'Other'),
        ],
        widget=forms.CheckboxSelectMultiple,  # Use CheckboxSelectMultiple widget
        required=False  # You can make it required if needed
    )
    project_progress = forms.CharField(max_length=100, required=False)
    class Meta:
        model = models.Project
        fields = [
            "name",
            "description",
            "team",
            "date_due",
            "technologies_used",
            "project_progress",
        ]
        widgets = {
            "name": forms.TextInput(attrs={"autocomplete": "off"}),
            "description": forms.Textarea(attrs={"autocomplete": "off"}),
            "date_due": DateWidget(),
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        user = self.request_user

        if not user.profile.is_manager:
            q1 = user.team_set.all()
            q2 = user.created_teams.all()
            q = q1 | q2
            self.fields["team"].queryset = q.distinct()

    def clean_team(self):
        team = self.cleaned_data["team"]
        user = self.request_user

        if not user.profile.is_manager:
            user_teams = user.team_set.all().union(user.created_teams.all())

            if team not in user_teams.all():
                msg = """You do not have permission to assign a project to a
                team that you are not a part of.
                """
                raise ValidationError(msg, code="Forbidden")
        return team


class CompleteProjectForm(custom_forms.CustomModelForm):
    class Meta:
        model = models.Project
        fields = [
            "date_completed",
        ]
        widgets = {"date_completed": DateWidget()}

projects/views.py
from datetime import date
from django.contrib.auth import mixins
from django.contrib.messages.views import SuccessMessageMixin
from django.shortcuts import reverse
from django.views import View, generic
from comments import forms as comment_forms
from comments import views as comment_views
from tasks.views import TaskCreateView
from django.contrib.auth.mixins import LoginRequiredMixin
from . import forms
from .models import Project



class ProjectListView(mixins.LoginRequiredMixin, generic.ListView):
    """Shows a list of all user projects"""

    model = Project

    def get_queryset(self):
        return Project.objects.all()


class ActiveProjectListView(mixins.LoginRequiredMixin, generic.ListView):
    """Shows a list of users active projects"""

    model = Project

    def get_queryset(self):
        return Project.objects.filter(team__members=self.request.user).filter(
            completed=False
        )


class CompletedProjectListView(mixins.LoginRequiredMixin, generic.ListView):
    """Shows a list of users completed projects"""

    model = Project

    def get_queryset(self):
        return Project.objects.filter(team__members=self.request.user).filter(
            completed=True
        )


class ProjectDetailView(LoginRequiredMixin, generic.DetailView):
    model = Project

    def get(self, request, *args, **kwargs):
        view = ProjectDetailDisplay.as_view()
        return view(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        view = comment_views.PostProjectComment.as_view()
        return view(request, *args, **kwargs)
    
class ProjectDetailDisplay(generic.DetailView):
    model = Project

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["form"] = comment_forms.ProjectCommentForm(
            user=self.request.user
        )
        return context


class ProjectCreateView(
    mixins.LoginRequiredMixin, SuccessMessageMixin, generic.CreateView,
):
    model = Project
    form_class = forms.ProjectForm
    success_message = "Project #%(id)s was created successfully"

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs.update({"user": self.request.user})
        return kwargs

    def get_success_message(self, cleaned_data):
        return self.success_message % dict(cleaned_data, id=self.object.id,)

    def form_valid(self, form):
        form.instance.created_by = self.request.user
        form.instance.modified_by = self.request.user
        form.instance.technologies_used = form.cleaned_data["technologies_used"]
        return super().form_valid(form)


class ProjectUpdateView(
    mixins.LoginRequiredMixin,
    mixins.UserPassesTestMixin,
    SuccessMessageMixin,
    generic.UpdateView,
):
    model = Project
    form_class = forms.ProjectForm
    success_message = "Project #%(id)s was updated successfully"

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs.update({"user": self.request.user})
        return kwargs

    def get_success_message(self, cleaned_data):
        return self.success_message % dict(cleaned_data, id=self.object.id,)

    def form_valid(self, form):
        form.instance.modified_by = self.request.user
        form.instance.technologies_used = form.cleaned_data["technologies_used"]
        form.instance.project_progress = form.cleaned_data["project_progress"]
        return super().form_valid(form)

    def test_func(self):
        project = self.get_object()
        user = self.request.user

        if project.was_created_by(user):
            return True
        return project.leader_is(user)


class ProjectCompleteView(
    mixins.LoginRequiredMixin,
    mixins.UserPassesTestMixin,
    SuccessMessageMixin,
    generic.UpdateView,
):
    model = Project
    form_class = forms.CompleteProjectForm
    initial = {
        "date_completed": date.today(),
    }
    success_message = "Project #%(id)s completed"

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs.update({"user": self.request.user})
        return kwargs

    def get_success_message(self, cleaned_data):
        return self.success_message % dict(cleaned_data, id=self.object.id,)

    def form_valid(self, form):
        form.instance.completed = True
        form.instance.completed_by = self.request.user
        form.instance.modified_by = self.request.user
        return super().form_valid(form)

    def test_func(self):
        project = self.get_object()
        user = self.request.user

        if project.was_created_by(user):
            return True
        return project.leader_is(user)


class ProjectDeleteView(
    mixins.LoginRequiredMixin, mixins.UserPassesTestMixin, generic.DeleteView,
):
    model = Project
    success_url = "/projects"

    def test_func(self):
        project = self.get_object()
        user = self.request.user

        if user.profile.is_demo_user:
            return False
        if project.was_created_by(user):
            return True
        return project.leader_is(user)


class ProjectAddTaskView(TaskCreateView):
    success_message = (
        "Task #{task_id} was successfully added to project #{project_id}."
    )

    def get_initial(self):
        initial = super().get_initial()

        project_pk = self.kwargs["pk"]
        # project = Project.objects.get(pk=project_pk)

        initial["project"] = project_pk
        return initial

    def get_success_message(self, cleaned_data):
        return self.success_message.format(
            task_id=self.object.id, project_id=self.kwargs["pk"]
        )

projects/templates/projects/project_confirm_delete.html
{% extends 'base/base_detail.html' %}

{% block title %}
  <title>Delete Project | National - PMS</title>
{% endblock title %}

{% block nav %}
  {% include 'projects/project_nav.html' %}
{% endblock nav %}

{% block cardContent %}
  <div class="card-header">
    <h2>Delete Project</h2>
  </div>
  <div class="card-body">
    <form method="post">
      {% csrf_token %}

      <h4 class="mb-3">
        Are you sure you want to delete Project#{{ project.id }} '{{ project.name }}'?
      </h4>

      <button type="submit" class="btn btn-danger">Delete</button>
      <a href="{% url 'project-detail' project.id %}" class="btn btn-secondary">Cancel</a>
    </form>
  </div>
{% endblock cardContent %}

projects/templates/projects/project_detail.html
{% extends 'base/base_detail.html' %}

{% load static %}

{% block title %}
  <title>Project {{ project.id }} | National - PMS</title>
{% endblock title %}

{% block nav %}
  {% include 'projects/project_nav.html' %}
{% endblock nav %}



{% block cardContent %}
  <div class="card-header">
    <h2>Project ID: {{ project.id }}&emsp;Project Name: {{ project.name }}</h2>
  </div>

  <div class="d-flex border-bottom">
    <div class="col-6" style="padding: 0.75rem 1.25rem">
      <strong>Team leader:</strong>&emsp;
      <a href="{% url 'profile' project.team.leader.username %}">{{ project.team.leader }}</a>
    </div>
    <div class="col-6 border-left" style="padding: 0.75rem 1.25rem">
      <strong>Team:</strong>&emsp;
      <a href="{% url 'team-detail' project.team.id %}">{{ project.team }}</a>
    </div>
  </div>

  <ul class="list-group list-group-flush border">
    <li class="list-group-item flex-fill">
      <strong>Team members:</strong>
      <ul class="list-group-item"> 
        {% for user in project.team.members.all %}
          <li class="mr-5"> Name :<a href="{% url 'profile' user.username %}"> {{ user.first_name }} {{ user.last_name }}</a>&emsp;
            Roll Number : <a href="{% url 'profile' user.username %}"> {{ user.profile.roll_number }}</a></li>
        {% endfor %}
        
      </ul>
    </li>
  </ul>

  <div class="card-body border-bottom">
    <h4>Detail</h4>
    <p>
      {% if project.description %}
        {{ project.description }}
      {% else %}
        <small class="text-muted">This project does not have a description yet.</small>
      {% endif %}
    </p>
    <h4>Technologies Used </h4>
    <p>
      {% if project.technologies_used %}
      {{ project.technologies_used|slice:"1:-1"|title}}
      {% else %}
        <small class="text-muted">This project does not have technologies added.</small>
      {% endif %}
    </p>
  </div>

  <div class="d-flex border-bottom">
    <div class="col-6" style="padding: 0.75rem 1.25rem">
      <strong>Date created:</strong>&emsp;
      {{ project.date_created }}
    </div>
    <div class="col-6 border-left" style="padding: 0.75rem 1.25rem">
      <strong>Created by:</strong>&emsp;
      <a href="{% url 'profile' project.created_by %}">{{ project.created_by }}</a>
    </div>
  </div>

  <div class="d-flex border-bottom">
    <div class="col-6" style="padding: 0.75rem 1.25rem">
      <strong>Last modified:</strong>&emsp;
      {{ project.date_modified }}
    </div>
    <div class="col-6 border-left" style="padding: 0.75rem 1.25rem">
      <strong>Modified by:</strong>&emsp;
      <a href="{% url 'profile' project.modified_by %}">{{ project.modified_by }}</a>
    </div>
  </div>

  <ul class="list-group list-group-flush border">
    <li class="list-group-item">
      <strong>Due:</strong>&emsp;

      {% if project.date_due %}
        {{ project.date_due }}&emsp;
        ({{ project.date_due|timeuntil }})
      {% else %}
        <small class="text-muted">This project does not a have a due date</small>
      {% endif %}
    </li>
  </ul>

  <div class="d-flex">
    {% if project.completed %}
      <div class="col-4 list-group-item-success" style="padding: 0.75rem 1.25rem">
        <strong>Status:</strong>&emsp;Completed
      </div>
      <div class="col-4 list-group-item-success border-left" style="padding: 0.75rem 1.25rem">
        <strong>Date completed:</strong>&emsp;{{ project.date_completed }}
      </div>
      <div class="col-4 list-group-item-success border-left" style="padding: 0.75rem 1.25rem">
        <strong>Completed by:</strong>&emsp;<a href="{% url 'profile' project.completed_by %}">{{ project.completed_by }}</a>
      </div>
    {% else %}
      <div class="flex-fill" style="padding: 0.75rem 1.25rem">
        <strong>Status:</strong>&emsp;In-Progress
      </div>
    {% endif %}
  </div>

  <div class="card-footer">
    {% if request.user == project.team.leader or request.user == project.created_by %}
      <a class="btn btn-primary" href="{% url 'project-update' project.id %}">Update</a>
      <a class="btn btn-primary" href="{% url 'project-add-task' project.id %}">Add Task</a>

      {% if not project.completed %}
        <a class="btn btn-success" href="{% url 'project-complete' project.id %}">Complete</a>
      {% endif %}

      {% if not request.user.profile.is_demo_user %}
        <a class="btn btn-danger float-right" href="{% url 'project-delete' project.id %}">Delete</a>
      {% endif %}

    {% elif request.user in project.team.members.all %}
      <a class="btn btn-primary" href="{% url 'project-add-task' project.id %}">Add Task</a>
    {% else %}
      <small class="text-muted">You do not have permission to edit this project.</small>
    {% endif %}
  </div>
{% endblock cardContent %}

{% block objects %}
  {% with project.task_set.all as task_list %}
    {% include 'projects/project_object_list.html' %}
  {% endwith %}
{% endblock objects %}

{% block comments %}
  {% with project.projectcomment_set.all as comments %}
    {% include 'comments/comments.html' %}
  {% endwith %}
{% endblock comments %}

{% block scripts %}
  {{ block.super }}
  <script src="{% static 'base/scripts/tableFunctions.js' %}"></script>
{% endblock scripts %}

projects/templates/projects/project_form.html
{% extends 'base/base_detail.html' %}

{% load crispy_forms_tags %}

{% block title %}
  {% if project %}
    <title>Project {{ project.id }} | National - PMS</title>
  {% else %}
    <title>Create Project | National - PMS</title>
  {% endif %}
{% endblock title %}

{% block nav %}
  {% include 'projects/project_nav.html' %}
{% endblock nav %}

{% block cardContent %}
  <div class="card-header">
    {% if project %}
      <h2>Project {{ project.id }}</h2>
    {% else %}
      <h2>Create Project</h2>
    {% endif %}
  </div>
  <div class="card-body">
    <form method="post">
      {% csrf_token %}
      {{ form|crispy }}
      <button type="submit" class="btn btn-primary">Save</button>
      <a class="btn btn-secondary" href="
        {% if request.resolver_match.url_name == 'create-project' %}
          {% url 'active-projects' %}
        {% else %}
          {% url 'project-detail' object.id %}
        {% endif %}
      ">Cancel</a>
    </form>
  </div>
{% endblock cardContent %}

projects/templates/projects/project_list.html
{% extends 'base/base_list.html' %}

{% block title %}
  <title>Projects | National - PMS</title>
{% endblock title %}

{% block nav %}
  {% include 'projects/project_nav.html' %}
{% endblock nav %}

{% block table %}
  <div class="row">
  {% if request.resolver_match.url_name == 'active-projects'%}
    <div class="col-md-8">
      <h4>Active Projects</h4>
      <p class="text-muted">Active projects you are a part of</p>
    </div>
  {% elif request.resolver_match.url_name == 'completed-projects'%}
    <div class="col-md-8">
      <h4>Completed Projects</h4>
      <p class="text-muted">Completed projects you are a part of</p>
    </div>
  {% elif request.resolver_match.url_name == 'all-projects'%}
    <div class="col-md-8">
      <h4>All Projects</h4>
      <p class="text-muted">All projects. Hint: try searching to filter</p>
    </div>
  {% endif %}

  {% with table_id="table1" row=True %}
    {% include 'projects/tables/generic_project_table.html' %}
  {% endwith %}
{% endblock table %}

projects/templates/projects/project_nav.html
<a
  href="{% url 'create-project' %}"
  class="btn btn-outline-primary btn-block mb-3
    {% if request.resolver_match.url_name == 'create-project' %}active{% endif %}">
  New Project
</a>

<div class="card mb-3">
  <div class="card-header text-center">
    <strong>My projects</strong>
  </div>

  <nav class="nav nav-pills flex-md-column">
    <a
      href="{% url 'active-projects' %}"
      class="nav-link
        {% if request.resolver_match.url_name == 'active-projects' %}active{% endif %}">
      My Active Projects
    </a>
    <a
      href="{% url 'completed-projects' %}"
      class="nav-link
        {% if request.resolver_match.url_name == 'completed-projects' %}active{% endif %}">
      My Completed Projects
    </a>
  </nav>
</div>

<div class="card mb-3">
  <div class="card-header text-center">
    <strong>All projects</strong>
  </div>

  <a
    href="{% url 'all-projects' %}"
    class="nav-link
      {% if request.resolver_match.url_name == 'all-projects' %}active{% endif %}">
    All Projects
  </a>
</div>

projects/templates/projects/project_object_list.html
<div class="nav nav-pills mb-3 position-absolute" id="nav-pill" role="tablist">
  <a class="nav-item nav-link" id="nav-task-table-tab" href="#task-table" data-toggle="pill" role="tab" aria-controls="task-table" aria-selected="false">Tasks</a>
</div>

<div class="tab-content" id="pills-tabContent">

  <!-- An empty div to take up space until a table is shown. This stops the navs from being hidden by the comments section. -->
  <div class="tab-pane fade show active mb-4">&emsp;</div>

  <div class="tab-pane fade" id="task-table" role="tabpanel" aria-lablledby="task-table">
    {% with 'table1' as table_id %}
      {% include 'tasks/tables/project_task_table.html' %}
    {% endwith %}
  </div>
</div>